"""models updated

Revision ID: 64904489b598
Revises: 406b99feadf9
Create Date: 2023-11-25 18:45:24.611861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64904489b598'
down_revision = '406b99feadf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre', sa.String(length=20), nullable=True))
        batch_op.drop_column('play_counter')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.add_column(sa.Column('play_counter', sa.INTEGER(), nullable=False))
        batch_op.drop_column('genre')

    # ### end Alembic commands ###
