"""updated song model

Revision ID: 726edaafb068
Revises: 
Create Date: 2023-11-18 10:14:40.030316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '726edaafb068'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.alter_column('album_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.alter_column('album_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
