export const REGISTER_ACTION = '[actions] registers user';
export const LOGIN_ACTION = '[actions] logs user in';
export const SET_USER_INFO_MUTATION = '[mutations] sets user token';
export const GET_USER_TOKEN = '[getters] gets auth user token';
export const IS_AUTHENTICATED = '[getters] checks if user is authenticated';
export const IS_CREATOR = '[getters] checks if user is creator';
export const IS_ADMIN = '[getters] checks if user is admin';
export const REGISTER_CREATOR_ACTION = '[actions] registers creator';
export const CREATE_PLAYLIST_ACTION = '[actions] creates new playlist';